{{/*
Expand the name of the chart.
*/}}
{{- define "device-service.name" -}}
{{- default .Chart.Name .Values.nameOverride | trunc 63 | trimSuffix "-" }}
{{- end }}

{{/*
Create a default fully qualified app name.
We truncate at 63 chars because some Kubernetes name fields are limited to this (by the DNS naming spec).
If release name contains chart name it will be used as a full name.
*/}}
{{- define "device-service.fullname" -}}
{{- if .Values.fullnameOverride }}
{{- .Values.fullnameOverride | trunc 63 | trimSuffix "-" }}
{{- else }}
{{- $name := default .Chart.Name .Values.nameOverride }}
{{- if contains $name .Release.Name }}
{{- .Release.Name | trunc 63 | trimSuffix "-" }}
{{- else }}
{{- printf "%s-%s" .Release.Name $name | trunc 63 | trimSuffix "-" }}
{{- end }}
{{- end }}
{{- end }}

{{/*
Create chart label.
*/}}
{{- define "device-service.chart" -}}
{{- printf "%s-%s" .Chart.Name .Chart.Version | replace "+" "_" | trunc 63 | trimSuffix "-" }}
{{- end }}

{{/*
Common labels.
*/}}
{{- define "device-service.labels" -}}
helm.sh/chart: {{ include "device-service.chart" . }}
{{ include "device-service.selectorLabels" . }}
{{- if .Chart.AppVersion }}
app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
{{- end }}
app.kubernetes.io/managed-by: {{ .Release.Service }}
{{- end }}

{{/*
Selector labels.
*/}}
{{- define "device-service.selectorLabels" -}}
app.kubernetes.io/name: {{ include "device-service.name" . }}
app.kubernetes.io/instance: {{ .Release.Name }}
app.kubernetes.io/component: backend
{{- end }}

{{/*
Service account name.
*/}}
{{- define "device-service.serviceAccountName" -}}
{{- if .Values.serviceAccount.create }}
{{- default (include "device-service.fullname" .) .Values.serviceAccount.name }}
{{- else }}
{{- default "default" .Values.serviceAccount.name }}
{{- end }}
{{- end }}

{{/*
CNPG cluster name.
*/}}
{{- define "device-service.cnpgClusterName" -}}
{{- printf "%s-postgres" (include "device-service.fullname" .) | trunc 63 | trimSuffix "-" }}
{{- end }}

{{/*
Name of the secret holding the DATABASE_URL.
- External mode  → secret created by this chart (or existing secret)
- CNPG mode      → the app secret generated by CloudNativePG
*/}}
{{- define "device-service.dbSecretName" -}}
{{- if .Values.database.external.enabled -}}
  {{- if .Values.database.external.existingSecret -}}
    {{- .Values.database.external.existingSecret.name -}}
  {{- else -}}
    {{- printf "%s-db-external" (include "device-service.fullname" .) -}}
  {{- end -}}
{{- else -}}
  {{- printf "%s-app" (include "device-service.cnpgClusterName" .) -}}
{{- end -}}
{{- end -}}

{{/*
Key inside the db url secret.
*/}}
{{- define "device-service.dbSecretKey" -}}
{{- if .Values.database.external.enabled -}}
  {{- if .Values.database.external.existingSecret -}}
    {{- .Values.database.external.existingSecret.key -}}
  {{- else -}}
    url
  {{- end -}}
{{- else -}}
  uri
{{- end -}}
{{- end -}}

{{/*
Image tag (defaults to chart appVersion).
*/}}
{{- define "device-service.imageTag" -}}
{{- .Values.image.tag | default .Chart.AppVersion }}
{{- end }}

{{/*
Name of the secret and key holding REDIS_URL.
- External mode (redis.external.enabled=true)
    → user-supplied secret or a secret created by this chart
- Valkey sub-chart mode
    → compute the URL from Valkey service name (no secret needed; pass as env var)
*/}}
{{- define "device-service.redisSecretName" -}}
{{- if .Values.redis.external.enabled -}}
  {{- if .Values.redis.external.existingSecret -}}
    {{- .Values.redis.external.existingSecret.name -}}
  {{- else -}}
    {{- printf "%s-redis-external" (include "device-service.fullname" .) -}}
  {{- end -}}
{{- end -}}
{{- end -}}

{{- define "device-service.redisSecretKey" -}}
{{- if .Values.redis.external.enabled -}}
  {{- if .Values.redis.external.existingSecret -}}
    {{- .Values.redis.external.existingSecret.key -}}
  {{- else -}}
    url
  {{- end -}}
{{- end -}}
{{- end -}}

{{/*
Built-in Valkey service name (primary standalone).
Bitnami Valkey names the primary service: <release>-valkey-primary
*/}}
{{- define "device-service.valkeyServiceName" -}}
{{- printf "%s-valkey" .Release.Name -}}
{{- end -}}

{{/*
Name of the secret holding the SMTP password.
- existingSecret mode  → user-supplied secret
- default              → secret created by this chart
*/}}
{{- define "device-service.smtpSecretName" -}}
{{- if .Values.app.smtp.existingSecret -}}
  {{- .Values.app.smtp.existingSecret.name -}}
{{- else -}}
  {{- printf "%s-smtp" (include "device-service.fullname" .) -}}
{{- end -}}
{{- end -}}

{{/*
Key inside the SMTP password secret.
*/}}
{{- define "device-service.smtpSecretPasswordKey" -}}
{{- if .Values.app.smtp.existingSecret -}}
  {{- .Values.app.smtp.existingSecret.passwordKey | default "password" -}}
{{- else -}}
  password
{{- end -}}
{{- end -}}
