{{- $smtpAuthType := .Values.app.smtp.authType | default "none" }}
{{- if and (ne $smtpAuthType "none") (not .Values.app.smtp.existingSecret) (not (empty (.Values.app.smtp.password | default ""))) }}
# Secret holding the SMTP password
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "device-service.fullname" . }}-smtp
  labels:
    {{- include "device-service.labels" . | nindent 4 }}
type: Opaque
stringData:
  password: {{ .Values.app.smtp.password | quote }}
{{- end }}
---
{{- if .Values.database.external.enabled }}
{{- if not .Values.database.external.existingSecret }}
# Secret holding the external DATABASE_URL
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "device-service.fullname" . }}-db-external
  labels:
    {{- include "device-service.labels" . | nindent 4 }}
  annotations:
    helm.sh/resource-policy: keep
type: Opaque
stringData:
  url: {{ .Values.database.external.url | quote }}
{{- end }}
{{- end }}
---
{{- if .Values.redis.external.enabled }}
{{- if not .Values.redis.external.existingSecret }}
# Secret holding the external Redis URL
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "device-service.fullname" . }}-redis-external
  labels:
    {{- include "device-service.labels" . | nindent 4 }}
type: Opaque
stringData:
  url: {{ .Values.redis.external.url | quote }}
{{- end }}
{{- end }}
